package com.guilherme.volleybar.presentation.ui
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import com.guilherme.volleybar.domain.model.*
import com.guilherme.volleybar.presentation.*
import com.guilherme.volleybar.presentation.theme.*

@Composable fun GameApp(store:GameStore){val state by store.state.collectAsState();VolleyBarTheme{Surface(Modifier.fillMaxSize()){if(state.loading)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()}else Column(Modifier.fillMaxSize().background(VolleyColors.Navy).padding(if(state.compact)6.dp else 16.dp)){if(!state.compact)Header(state){store.dispatch(it)};state.message?.let{Snackbar(action={TextButton({store.dispatch(GameAction.ClearMessage)}){Text("OK")}}){Text(it)}};when(val screen=state.screen){GameScreen.Home->Home(state){store.dispatch(it)};GameScreen.Team->TeamView(state){store.dispatch(it)};is GameScreen.PlayerDetails->Details(state,screen.id){store.dispatch(it)};GameScreen.Match->MatchView(state){store.dispatch(it)};GameScreen.Result->ResultView(state){store.dispatch(it)}}}}}}
@Composable private fun Header(state:GameUiState,on:(GameAction)->Unit){Row(Modifier.fillMaxWidth().padding(bottom=12.dp),verticalAlignment=Alignment.CenterVertically){Text("🏐 VOLLEYBAR",fontSize=24.sp,fontWeight=FontWeight.Black,color=VolleyColors.Cyan);Spacer(Modifier.weight(1f));TextButton({on(GameAction.Navigate(GameScreen.Home))}){Text("INÍCIO")};TextButton({on(GameAction.Navigate(GameScreen.Team))}){Text("MEU TIME")};if(state.progress?.currentMatch!=null)TextButton({on(GameAction.Navigate(GameScreen.Match))}){Text("PARTIDA")}}}
@Composable private fun Home(s:GameUiState,on:(GameAction)->Unit){val p=s.progress!!;val average=(p.team.averageLevel*10).toInt()/10.0;Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("VOLLEY",fontSize=64.sp,fontWeight=FontWeight.Black,color=VolleyColors.Cyan);Text("BAR",fontSize=64.sp,fontWeight=FontWeight.Black,color=VolleyColors.Pink);Text("GERENCIE • EVOLUA • DOMINE A REDE",color=VolleyColors.Yellow);Spacer(Modifier.height(24.dp));PixelPanel{Text("${p.wins} VITÓRIAS  •  ${p.losses} DERROTAS  •  NÍVEL MÉDIO $average");Text("${p.teamTrainingPoints} PONTOS DO TIME • ${p.matchesPlayed} JOGOS")};Spacer(Modifier.height(16.dp));PixelButton("Jogar",{on(GameAction.StartMatch)},Modifier.width(260.dp));Spacer(Modifier.height(8.dp));PixelButton("Meu time",{on(GameAction.Navigate(GameScreen.Team))},Modifier.width(260.dp));if(p.currentMatch!=null){Spacer(Modifier.height(8.dp));PixelButton("Continuar partida",{on(GameAction.Navigate(GameScreen.Match))},Modifier.width(260.dp))}}}
@Composable private fun TeamView(s:GameUiState,on:(GameAction)->Unit){val team=s.progress!!.team;Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("ELENCO / 12 ATLETAS",fontSize=22.sp,fontWeight=FontWeight.Bold);Text("Titulares ${team.starters.size}/6 • ${com.guilherme.volleybar.domain.usecase.LineupRules.validate(team)?:"Formação pronta!"}",color=VolleyColors.Yellow)};PixelButton("Iniciar partida",{on(GameAction.StartMatch)})};Spacer(Modifier.height(10.dp));LazyVerticalGrid(GridCells.Adaptive(225.dp),horizontalArrangement=Arrangement.spacedBy(10.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(team.players,key={it.id}){p->PlayerCard(p,{on(GameAction.ToggleStarter(p.id))},{on(GameAction.Navigate(GameScreen.PlayerDetails(p.id)))})}}}}
@Composable private fun Details(s:GameUiState,id:String,on:(GameAction)->Unit){val p=s.progress!!.team.players.first{it.id==id};Column(Modifier.verticalScroll(rememberScrollState())){TextButton({on(GameAction.Navigate(GameScreen.Team))}){Text("← VOLTAR")};PixelPanel(Modifier.widthIn(max=620.dp).align(Alignment.CenterHorizontally)){Row(verticalAlignment=Alignment.CenterVertically){PlayerSprite(p,Modifier.size(110.dp));Column{Text("#${p.number} ${p.name}",fontSize=30.sp,fontWeight=FontWeight.Black,color=VolleyColors.Yellow);Text("${p.position.label} • NÍVEL ${p.level}");Text("XP ${p.experience}/${p.xpForNextLevel}");Text("PONTOS: ${p.trainingPoints}",color=VolleyColors.Neon)}};Spacer(Modifier.height(12.dp));AttributeType.entries.forEach{type->val value=p.attributes.value(type);Row(verticalAlignment=Alignment.CenterVertically){Text(type.label.uppercase(),Modifier.width(140.dp));PixelProgress(value/100f,if(value>=75)VolleyColors.Neon else VolleyColors.Cyan,Modifier.weight(1f));Text(" $value",Modifier.width(44.dp));PixelButton("+",{on(GameAction.Upgrade(p.id,type))},enabled=p.trainingPoints>0&&value<100)}}}}}
@Composable private fun MatchView(s:GameUiState,on:(GameAction)->Unit){val m=s.progress?.currentMatch?:return;Column{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text("VOLLEYBAR ${m.homeSets}  •  ${m.awaySets} ${m.opponent.name}",fontSize=22.sp,fontWeight=FontWeight.Black);Row{TextButton({on(GameAction.ToggleCompact)}){Text(if(s.compact)"EXPANDIR" else "COMPACTO")};PixelButton(if(s.auto)"Pausar" else "Auto",{on(GameAction.ToggleAuto)});Spacer(Modifier.width(8.dp));PixelButton("Próximo rally",{on(GameAction.Rally)},enabled=!s.auto)}};val set=m.sets.last();Text("SET ${m.sets.size}   ${set.homePoints} — ${set.awayPoints}",fontSize=30.sp,color=VolleyColors.Yellow,modifier=Modifier.align(Alignment.CenterHorizontally));VolleyballCourt(m,Modifier.fillMaxWidth().weight(1f));if(!s.compact){Spacer(Modifier.height(8.dp));PixelPanel(Modifier.fillMaxWidth().heightIn(max=150.dp)){Text("TRANSMISSÃO",fontWeight=FontWeight.Bold,color=VolleyColors.Cyan);m.events.takeLast(5).reversed().forEach{Text("› $it",fontSize=13.sp)}}}}}
@Composable private fun ResultView(s:GameUiState,on:(GameAction)->Unit){val r=s.result?:return;val mvp=s.progress!!.team.players.first{it.id==r.mvpId};Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text(if(r.won)"VITÓRIA!" else "QUASE!",fontSize=54.sp,fontWeight=FontWeight.Black,color=if(r.won)VolleyColors.Neon else VolleyColors.Pink);Text(r.sets.joinToString("  "){"${it.homePoints}–${it.awayPoints}"},fontSize=24.sp);Spacer(Modifier.height(16.dp));PixelPanel{Text("MVP: ${mvp.name}",color=VolleyColors.Yellow,fontWeight=FontWeight.Bold);Text("Titulares +${r.reward.starterXp} XP • Reservas +${r.reward.reserveXp} XP");Text("MVP +${r.reward.mvpBonusXp} XP • Time +${r.reward.teamTrainingPoints} PT");if(r.levelUps.isNotEmpty())Text("LEVEL UP: ${r.levelUps.joinToString()}",color=VolleyColors.Neon)};Spacer(Modifier.height(14.dp));Row{PixelButton("Meu time",{on(GameAction.Navigate(GameScreen.Team))});Spacer(Modifier.width(8.dp));PixelButton("Nova partida",{on(GameAction.StartMatch)})}}}
